services:
  db:
    image: postgres:16.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=dev_db

  app-service:
    build: ./src
    command: uv run new_proj/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/app/
    develop:
      watch:
          - action: sync
            path: src/new_proj/
            target: /app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  app-migrate:
    build: ./src
    command: uv run new_proj/manage.py migrate
    volumes:
      - ./src/:/app/
    env_file:
      - ./.env
    depends_on:
      - db

  app-superuser:
    build: ./src
    command: uv run new_proj/manage.py createsuperuser --no-input --username 236523  --email 236523@admin.co
    volumes:
      - ./src/:/app/
    env_file:
      - ./.env
    depends_on:
      - app-migrate
      - db

  pgadmin:
    image: dpage/pgadmin4:9.8
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
  
volumes:
  postgres_data:
